name: Notify Cron

on:
  workflow_dispatch:      
  schedule:
    - cron: '0 1 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip    
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      
    - name: Run Main
      env:
        APP_GCS_URL: ${{ secrets.APP_GCS_URL }}
        APP_SLACK_URL: ${{ secrets.APP_SLACK_URL }}
      run: |
        python main.py

    - name: Run Change push
      run: |
        s=`git status -s`
        if [ -z "$s" ]; then
          exit 0
        fi
        git config --global user.email "workflow@example.com"
        git config --global user.name "workflow user"
        git add save.log
        git commit -m "update save.log"
        git status
        git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        
